export const Component = {
  RestApplication: Symbol.for("RestApplication"),
  Logger: Symbol.for("Logger"),
  Config: Symbol.for("Config"),
  DatabaseClient: Symbol.for("DatabaseClient"),
  ExceptionFilter: Symbol.for("ExceptionFilter"),
  UserModel: Symbol.for("UserModel"),
  UserService: Symbol.for("UserService"),
  UserController: Symbol.for("UserController"),
  OfferService: Symbol.for("OfferService"),
  OfferModel: Symbol.for("OfferModel"),
  OfferController: Symbol.for("OfferController"),
  CommentService: Symbol.for("CommentService"),
  CommentModel: Symbol.for("CommentModel"),
  CommentController: Symbol.for("CommentController"),
} as const;
