export const OfferDtoConstants = {
  MIN_TITLE_LENGTH: 10,
  MAX_TITLE_LENGTH: 100,
  MIN_DESCRIPTION_LENGTH: 20,
  MAX_DESCRIPTION_LENGTH: 1024,
  MIN_ROOMS_NUMBER: 1,
  MAX_ROOMS_NUMBER: 8,
  MIN_GUESTS_NUMBER: 1,
  MAX_GUESTS_NUMBER: 10,
  MIN_PRICE: 100,
  MAX_PRICE: 100000,
  IMAGES_NUMBER: 6,
};
